= Developing Restful APIs: A Comprehensive Set of Guidelines by SailPoint, adapted from https://github.com/zalando/restful-api-guidelines[Zalando's RESTful API Guidelines]

Latest published version:
https://sailpoint-oss.github.io/sailpoint-api-guidelines/[*HTML*],
https://github.com/sailpoint-oss/sailpoint-api-guidelines/blob/main/docs/sailpoint-guidelines.pdf[*PDF*],
https://github.com/sailpoint-oss/sailpoint-api-guidelines/blob/main/docs/sailpoint-guidelines.epub[*EPUB3*]

== Purpose

Great RESTful APIs look like they were designed by a single team. This
promotes API adoption, reduces friction, and enables clients to use them
properly. To build APIs that meet this standard, and to answer many
common questions encountered along the way of RESTful API development,
the SailPoint API Guild has created this comprehensive set of guidelines.
We have shared it with you to inspire additional discussion and
refinement within and among your teams, and contribute our learnings and
suggestions to the tech community at large.

== Usage

Feel free to use these guidelines as a guidance for your own
development. Note that we encourage our own teams to use them in order
to challenge their APIs. As such, you should consider this to be a
living, evolving document. We will revise and update based on our
learnings and experiences.

== Build

=== Build HTML site, PDF and EPUB3 locally

You must have Docker installed and running before executing the below command.

[source,bash]
----
make all
----

=== Generate Custom CSS

In order to generate custom CSS we have to use http://asciidoctor.org/docs/user-manual/#stylesheet-factory[`stylesheet-factory`]

This script clones the factory repository, installs the dependencies and generates CSS based in the `zalando.scss`

[source,bash]
----
.scripts/build-css.sh
----

== License

Credit goes to the Zolando Team for these guidelines. https://github.com/zalando/restful-api-guidelines[Zalando]

We have made slight modifications to the Zolando guidelines to fit our companies needs.

We have published these guidelines under the CC-BY (Creative commons
Attribution 4.0) license. Please see link:LICENSE[LICENSE file].
