[[common-data-types]]
= Common data types

Definitions of data objects that are good candidates for wider usage. Below you can find a list of common data types
used in the guideline:

* <<173, Money object>>
* <<176, Problem object>>
* <<address-fields, Address object>>


[#173]
== {MUST} use the common money object

Use the following common money structure:

[source,yaml]
----
include::../models/money-1.0.0.yaml[]
----

APIs are encouraged to include a reference to the global schema for Money.

[source,yaml]
----
SalesOrder:
  properties:
    grand_total:
      $ref: 'https://opensource.zalando.com/restful-api-guidelines/money-1.0.0.yaml#/Money'
----

Please note that APIs have to treat Money as a closed data type, i.e. it's not meant to be used in an inheritance hierarchy. That means the following usage is not allowed:

[source,json]
----
{
  "amount": 19.99,
  "currency": "EUR",
  "discounted_amount": 9.99
}
----

=== Cons

* Violates the https://en.wikipedia.org/wiki/Liskov_substitution_principle[Liskov Substitution Principle]
* Breaks existing library support, e.g. https://github.com/zalando/jackson-datatype-money[Jackson Datatype Money]
* Less flexible since both amounts are coupled together, e.g. mixed currencies are impossible

A better approach is to favor https://en.wikipedia.org/wiki/Composition_over_inheritance[composition over inheritance]:

[source,json]
----
{
    "price": {
      "amount": 19.99,
      "currency": "EUR"
    },
    "discounted_price": {
      "amount": 9.99,
      "currency": "EUR"
    }
}
----

=== Pros

* No inheritance, hence no issue with the substitution principle
* Makes use of existing library support
* No coupling, i.e. mixed currencies is an option
* Prices are now self-describing, atomic values

=== Notes

Please be aware that some business cases (e.g. transactions in Bitcoin) call for a higher precision, so applications must be prepared to accept values with unlimited precision, unless explicitly stated otherwise in the API specification.

Examples for correct representations (in EUR):

* `42.20` or `42.2` = 42 Euros, 20 Cent
* `0.23` = 23 Cent
* `42.0` or `42` = 42 Euros
* `1024.42` = 1024 Euros, 42 Cent
* `1024.4225` = 1024 Euros, 42.25 Cent

Make sure that you don’t convert the "amount" field to `float` /
`double` types when implementing this interface in a specific language
or when doing calculations. Otherwise, you might lose precision.
Instead, use exact formats like Java’s
https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html[`BigDecimal`].
See http://stackoverflow.com/a/3730040/342852[Stack Overflow] for more
info.

Some JSON parsers (NodeJS’s, for example) convert numbers to floats by default.
After discussing the pros and cons we’ve decided on "decimal" as our amount
format. It is not a standard OpenAPI format, but should help us to avoid parsing
numbers as float / doubles.


[#174]
== {MUST} use common field names and semantics

TBD

