[[data-formats]]
= Data formats


[#167]
== {MUST} use JSON as payload data interchange format

Use JSON ({RFC-7159}[RFC 7159]) to represent structured (resource) data 
passed with HTTP requests and responses as body payload.
The JSON payload must use a JSON object as top-level data 
structure (if possible) to allow for future extension. This also applies to
collection resources, where you ad-hoc would use an array -- see also
<<110>>.

Additionally, the JSON payload must comply to the more restrictive Internet JSON ({RFC-7493}[RFC 7493]),
particularly

* {RFC-7493}#section-2.1[Section 2.1] on encoding of characters, and
* {RFC-7493}#section-2.3[Section 2.3] on object constraints.

As a consequence, a JSON payload must

* use {RFC-7493}#section-2.1[`UTF-8` encoding]
* consist of {RFC-7493}#section-2.1[valid Unicode strings], i.e. must not
  contain non-characters or surrogates, and
* contain only {RFC-7493}#section-2.3[unique member names] (no duplicate
  names).


[#168]
== {MAY} pass non-JSON media types using data specific standard formats

TBD


[#172]
== {SHOULD} use standard media types

You should use standard media types (defined in {media-types}[media type registry] 
of Internet Assigned Numbers Authority (IANA)) as `content-type` (or `accept`) header 
information. More specifically, for JSON payload you should use the standard media type 
`application/json` (or `application/problem+json` for <<176>>).

You should avoid using custom media types like `application/x.sailpoint.article+json`. 
Custom media types beginning with `x` bring no advantage compared to the
standard media type for JSON, and make automated processing more difficult.


[#239]
=== {MUST} encode embedded binary data in `base64url`

Exposing binary data using an alternative media type is generally preferred.
See <<168,the rule above>>.

If an alternative content representation is not desired then binary data should
be embedded into the JSON document as a `base64url`-encoded string property
following {RFC-7493}#section-4.4[RFC 7493 Section 4.4].


[#238]
== {MUST} use standardized property formats

https://json-schema.org/understanding-json-schema/reference/string.html#format[JSON Schema] 
and https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types[OpenAPI] 
define several data formats, e.g. `date`, `time`, `email`, and `url`, based on ISO and IETF standards.
The following table lists these formats including additional formats useful in an e-commerce environment. 
You *should* use these formats, whenever applicable.

[cols="10%,25%,25%,40%",options="header",]
|=====================================================================
| `type` | `format` | Specification | Example
| `integer` | <<171, `int32`>> |  | `7721071004`
| `integer` | <<171, `int64`>> |  | `772107100456824`
| `integer` | <<171, `bigint`>> |  | `77210710045682438959`
| `number` | <<171, `float`>> | {IEEE-754-2008}[IEEE 754-2008] | `3.1415927`
| `number` | <<171, `double`>> | {IEEE-754-2008}[IEEE 754-2008] | `3.141592653589793`
| `number` | <<171, `decimal`>> |  | `3.141592653589793238462643383279`
| `string` | <<170, `bcp47`>> | {BCP47}[BCP 47] | `"en-DE"`
| `string` | `byte` | {RFC-7493}[RFC 7493] | `"dGVzdA=="`
| `string` | <<126, `date`>> | {RFC-3339}[RFC 3339] | `"2019-07-30"`
| `string` | <<126, `date-time`>> | {RFC-3339}[RFC 3339] |`"2019-07-30T06:43:40.252Z"`
| `string` | `email` | {RFC-5322}[RFC 5322] | `"example@sailpoint.de"`
| `string` | `gtin-13` | {GTIN}[GTIN] | `"5710798389878"`
| `string` | `hostname` | {RFC-1034}[RFC 1034] | `"www.sailpoint.de"`
| `string` | `ipv4` | {RFC-2673}[RFC 2673] | `"104.75.173.179"`
| `string` | `ipv6` | {RFC-2673}[RFC 2673] | `"2600:1401:2::8a"`
| `string` | <<170, `iso-3166`>> | {ISO-3166-1-a2}[ISO 3166-1 alpha-2] | `"DE"`
| `string` | <<173, `iso-4217`>> | {ISO-4217}[ISO 4217] | `"EUR"`
| `string` | <<170, `iso-639`>> | {ISO-639-1}[ISO 639-1] | `"de"`
| `string` | `json-pointer` | {RFC-6901}[RFC 6901] | `"/items/0/id"`
| `string` | `password` |  | `"secret"`
| `string` | `regex` | {ECMA-262}[ECMA 262] | `"^[a-z0-9]+$"`
| `string` | <<126, `time`>> | {RFC-3339}[RFC 3339] | `"06:43:40.252Z"`
| `string` | `uri` | {RFC-3986}[RFC 3986] | `"https://www.sailpoint.de/"`
| `string` | `uri-template` | {RFC-6570}[RFC 6570] | `"/users/\{id\}"`
| `string` | `uuid` | {RFC-4122}[RFC 4122] | `"e2ab873e-b295-11e9-9c02-..."`
|=====================================================================

*Remark:* Please note that this list of standard data formats is not exhaustive 
and everyone is encouraged to propose additions.


[#169]
== {MUST} use standard date and time formats


[[json-payload]]
=== JSON payload

Read more about date and time format in <<126>>.


[[http-headers]]
=== HTTP headers

Http headers including the proprietary headers use the
{RFC-7231}#section-7.1.1.1[HTTP date format defined in RFC 7231].


[#128]
[#170]
== {MUST} use standards for country, language and currency codes

Use the following standard formats for country, language and currency
codes:

* Country codes: {ISO-3166-1-a2}[ISO 3166-1-alpha2] two letter country codes
** Hint: It is "GB", not "UK", even though "UK" has seen some use at sailpoint
* Language codes: {ISO-639-1}[ISO 639-1] two letter language codes
* Language variant tags: {BCP47}[BCP 47] 
** It is a compatible extension of {ISO-639-1}[ISO 639-1], providing additional 
   information for language usage, like region (using {ISO-3166-1-a2}[ISO 3166-1]), 
   variant, script and others.
* Currency codes:  {ISO-4217}[ISO 4217] three letter currency codes


[#171]
== {MUST} define format for number and integer types icon:check-square[text="Test" role="lime"]

Whenever an API defines a property of type `number` or `integer`, the
precision must be defined by the format as follows to prevent clients
from guessing the precision incorrectly, and thereby changing the value
unintentionally:

[cols="15%,15%,70%",options="header",]
|=====================================================================
|type |format |specified value range
|integer |int32 |integer between pass:[-2<sup>31</sup>] and pass:[2<sup>31</sup>]-1
|integer |int64 |integer between pass:[-2<sup>63</sup>] and pass:[2<sup>63</sup>]-1
|integer |bigint |arbitrarily large signed integer number
|number |float |{IEEE-754-2008}[IEEE 754-2008/ISO 60559:2011] binary32 decimal number
|number |double |{IEEE-754-2008}[IEEE 754-2008/ISO 60559:2011] binary64 decimal number
|number |decimal |arbitrarily precise signed decimal number
|=====================================================================

The precision must be translated by clients and servers into the most
specific language types. E.g. for the following definitions the most
specific language types in Java will translate to `BigDecimal` for
`Money.amount` and `int` or `Integer` for the `OrderList.page_size`:

[source,yaml]
----
components:
  schemas:
    Money:
      type: object
      properties:
        amount:
          type: number
          description: Amount expressed as a decimal number of major currency units
          format: decimal
          example: 99.95
       ...
    
    OrderList:
      type: object
      properties:
        page_size:
          type: integer
          description: Number of orders in list
          format: int32
          example: 42
----


[#324]
== {MUST} use proper description format for the `filters` query param

The OpenAPI specification does not provide dedicated properties for defining filters,
so filters must be defined in the description of the `filters` query param.  Our users 
and our tooling rely on filter descriptions following a strict format.  The following
snippet is an example of how to properly format the description for `filters`.

```yaml
- in: query
  name: filters
  schema:
    type: string
  description: >-
    Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)


    Filtering is supported for the following fields and operators:
    

    **id**: *eq, in*


    **name**: *eq, sw*


    **created**: *gt, lt, ge, le*
    
    
    **modified**: *gt, lt, ge, le*


    **owner.id**: *eq, in*


    **requestable**: *eq*


    **source.id**: *eq, in*
  example: name eq "SailPoint Support"
  required: false
```

- Always include the first two lines in your description to point users towards the extended documenation.
- Always use two new lines between lines. The use of one new line will result in the text not displaying on separate lines in the API documentaiton.
- Always bold the property name using two asterisks before and after the name.
- Only document one property per line.
- Always italicize the operators by using a single asterisk before an after the list of operators.
- Only use the operators https://developer.sailpoint.com/idn/api/standard-collection-parameters#filter-syntax[listed here]. If you are introducing a new operator not in the list, please contact the Developer Relations team to update the list.
- Always use a comma and a space to separate operators.
- Do not add any additional text in the description, such as examples, clarifications, etc.


[#325]
== {MUST} use proper description format for the `sorters` query param

The OpenAPI specification does not provide dedicated properties for defining sorter,
so sorters must be defined in the description of the `sorters` query param.  Our users 
and our tooling rely on filter descriptions following a strict format.  The following
snippet is an example of how to properly format the description for `sorters`.

```yaml
- in: query
  name: sorters
  schema:
    type: string
    format: comma-separated
  description: >-
    Sort results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#sorting-results)


    Sorting is supported for the following fields: **name, created, modified**
  example: name,-modified
  required: false
```

- Always include the first line in your description to point users towards the extended documenation.
- Always use two new lines between lines. The use of one new line will result in the text not displaying on separate lines in the API documentaiton.
- The second line must start with "Sorting is supported for the following fields:"
- Wrap all supported properties in double asterisks to make them bold.
- Use a comma and a space to separate supported properties.
- Do not add any additional lines or text in the description. There should only be two lines: the extended documentation and the list of supporter properties.