[[general-guidelines]]
= General guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.


[#100]
== {SHOULD} follow API first principle

You must follow the <<api-first, API First Principle>>, more specifically: 

* You should define APIs first, before coding its implementation, 
  using OpenAPI as specification language

* You should call for early review feedback from peers and client developers


[#101]
== {MUST} provide API specification using OpenAPI

We use the https://swagger.io/specification/[OpenAPI specification, role=external, window=_blank] as the standard to define API specification files.  
OpenAPI 3.0 must be supported, but you MAY support other versions, like Swagger 2.

The API specification files should be subject to version control using a source code management system.

You <<192, must>> publish the component API specification with the deployment of the implementing service, and, hence, 
make it discoverable for the appropriate group via our https://developer.sailpoint.com/[API Portal, role=external, window=_blank].


[#301]
== {MUST} provide detailed API description
	
Within the API specification, you must provide sufficient information in 
the description of the API to facilitate proper usage.  This may include:

* API scope, purpose, and use cases
* Major edge cases
* Major dependencies


[#102]
== {SHOULD} provide API user manual

In addition to the API Specification, it is good practice to provide a separate API 
user manual to improve client developer experience, especially of engineers that are 
less experienced in using this API. A helpful API user manual typically describes 
the following API aspects:

* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and dependencies - including figures and sequence flows

The user manual must be published online, e.g. via our documentation hosting 
platform service. Please do not forget to include a link to the API user 
manual into the API specification using the #/externalDocs/url property.

[NOTE]
====
This manual does not have to be created by engineering, but could be created by a documentation team, Developer Relations or by community effort.
It is important to provide extra documentation for our developers to reduce the number of support related questions that come in. 
====

[#103]
== {MUST} write APIs using U.S. English
