[[general-guidelines]]
= General guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.

[#301]
== {MUST} follow SailPoint API Guidelines

You must design your APIs consistently with these guidelines; use our API linter for automated rule checks, but not every rule can be automated.

[#100]
== {SHOULD} follow API first principle

You should follow the <<api-first, API First Principle>>, more specifically: 

* You should define APIs first, before coding their implementation, 
  using <<101, OpenAPI as the specification language>>

* You should call for early review feedback from peers and client developers


[#101]
== {MUST} provide API specification using OpenAPI

We use the https://swagger.io/specification/[OpenAPI specification, role=external, window=_blank] as the standard to define API specification files.  
OpenAPI 3.0 must be supported, but you MAY support other versions, like Swagger 2.

The API specification files should be subject to version control using a source code management system.

You <<192, must>> publish the component API specification with the deployment of the implementing service, and, hence, 
make it discoverable for the appropriate group via our https://developer.sailpoint.com/[API Portal, role=external, window=_blank].


[#302]
== {MUST} provide detailed API description
	
Within the API specification, you must provide sufficient information in 
the description of the API to facilitate proper usage.  This may include:

* API scope, purpose, and use cases
* Major edge cases
* Major dependencies


[#102]
== {SHOULD} provide API user manual

In addition to the API Specification, it is good practice to provide a separate API 
user manual to improve client developer experience, especially of engineers that are 
less experienced in using this API. A helpful API user manual typically describes 
the following API aspects:

* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and dependencies - including figures and sequence flows

The user manual must be published online, e.g. via our documentation hosting 
platform service. Please do not forget to include a link to the API user 
manual into the API specification using the #/externalDocs/url property.

[NOTE]
====
This manual does not have to be created by engineering, but could be created by a documentation team, Developer Relations or by community effort.
It is important to provide extra documentation for our developers to reduce the number of support related questions that come in. 
====

[#303]
== {MUST} describe every parameter and property

Every query/path parameter and request/response property in the API specification must have a description

[#304]
== {MUST} provide an example for every parameter and property

Every query/path parameter and request/response property in the API specification must have an accurate example.  
An accurate example will show the API consumer what an input/output value will realistically look like, and could even be used in a real request/response.
However, take care to not use personally identifiable information or secrets in examples.

Every operation (POST, PUT, PATCH, etc) may define one or more operation level examples.

[#305]
== {SHOULD} keep operation summaries at five or less words

Certain tools, like Postman, have a limit on how many words can be displayed within the operation summary.  
It is helpful for consumers to have short summaries that describe the operation at its most basic level to improve readability for consumers.

[#400]
== {MUST} provide a valid operationId in camelCase for each operation

`operationId` is a unique string used to identify an operation. These IDs must be unique among all operations described in your API.

Certain tools, like the OpenAPI Generator use this value to name the corresponding methods in code.

The following `listAccessProfiles` is an example of an operationId.

[source,yaml]
----
get:
  operationId: listAccessProfiles
  tags:
    - Access Profiles
  summary: List Access Profiles
  description: >-
    This API returns a list of Access Profiles.
----

Use this guide when creating your operationIds. Your operationId must start with one of the approved values for each method.

*GET* methods that return an array
[format=csv]
|===
`compare`,`export`,`get`
`list`,`search`,
|===

*GET* methods that return a single result
[format=csv]
|===
`get`,`search`,`test`
|===

*POST* methods
[format=csv]
|===
`approve`,`cancel`,`complete`
`create`,`delete`,`disable`
`enable`,  `export`,`hide`
`import`,  `move`,  `ping`
`reject`,  `reset`, `search`
`send`,    `set`,    `show`
`start`,   `submit`,`sync`
`unlock`,  `unregister`, `update`
|===

*PUT* methods
[format=csv]
|===
`put`,`set`,
|===

*PATCH* methods
[format=csv]
|===
`patch`,`update`,
|===

*DELETE* methods
[format=csv]
|===
`delete`,`remove`,
|===


[#103]
== {MUST} write APIs using U.S. English
