[[general-guidelines]]
= General guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.

[#301]
== {MUST} follow SailPoint API Guidelines

You must design your APIs consistently with these guidelines; use our API linter for automated rule checks, but not every rule can be automated.

[#100]
== {SHOULD} follow API first principle

You should follow the <<api-first, API First Principle>>, more specifically: 

* You should define APIs first, before coding their implementation, 
  using <<101, OpenAPI as the specification language>>

* You should call for early review feedback from peers and client developers


[#101]
== {MUST} provide API specification using OpenAPI

We use the https://swagger.io/specification/[OpenAPI specification, role=external, window=_blank] as the standard to define API specification files.  
OpenAPI 3.0 must be supported, but you MAY support other versions, like Swagger 2.

The API specification files should be subject to version control using a source code management system.

You <<192, must>> publish the component API specification with the deployment of the implementing service, and, hence, 
make it discoverable for the appropriate group via our https://developer.sailpoint.com/[API Portal, role=external, window=_blank].


[#302]
== {MUST} provide detailed API description
	
Within the API specification, you must provide sufficient information in 
the description of the API to facilitate proper usage.  This may include:

* API scope, purpose, and use cases
* Major edge cases
* Major dependencies


[#102]
== {SHOULD} provide API user manual

In addition to the API Specification, it is good practice to provide a separate API 
user manual to improve client developer experience, especially of engineers that are 
less experienced in using this API. A helpful API user manual typically describes 
the following API aspects:

* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and dependencies - including figures and sequence flows

The user manual must be published online, e.g. via our documentation hosting 
platform service. Please do not forget to include a link to the API user 
manual into the API specification using the #/externalDocs/url property.

[NOTE]
====
This manual does not have to be created by engineering, but could be created by a documentation team, Developer Relations or by community effort.
It is important to provide extra documentation for our developers to reduce the number of support related questions that come in. 
====

[#303]
== {MUST} describe every parameter and property icon:check-square[text="Test" role="lime"]

Every query/path parameter and request/response property in the API specification must have a description

[#304]
== {MUST} provide an example for every parameter and property icon:check-square[text="Test" role="lime"]

Every query/path parameter and request/response property in the API specification must have an accurate example.  
An accurate example will show the API consumer what an input/output value will realistically look like, and could even be used in a real request/response.
However, take care to not use personally identifiable information or secrets in examples.

Every operation (POST, PUT, PATCH, etc) may define one or more operation level examples.

[#305]
== {SHOULD} keep operation summaries at five or less words icon:check-square[text="Test" role="lime"]

Certain tools, like Postman, have a limit on how many words can be displayed within the operation summary.  
It is helpful for consumers to have short summaries that describe the operation at its most basic level to improve readability for consumers.

[#400]
== {MUST} provide a valid operationId in camelCase for each operation icon:check-square[text="Test" role="lime"]

`operationId` is a unique string used to identify an operation. These IDs must be unique among all operations described in your API.

Certain tools, like the OpenAPI Generator use this value to name the corresponding methods in code.

The following `listAccessProfiles` is an example of an operationId.

[source,yaml]
----
get:
  operationId: listAccessProfiles
  tags:
    - Access Profiles
  summary: List Access Profiles
  description: >-
    This API returns a list of Access Profiles.
----

Use this guide when creating your operationIds. Your operationId must start with one of the approved values for each method.

*GET* methods that return an array

* compare
* export
* get
* list
* search

*GET* methods that return a single result

* get
* search
* test

*POST* methods

* approve
* cancel
* complete
* create
* delete
* disable
* enable
* export
* hide
* import
* move
* ping
* reject
* reset
* search
* send
* set
* show
* start
* submit
* sync
* unlock
* unregister
* update

*PUT* methods

* put
* set

*PATCH* methods

* patch
* update

*DELETE* methods

* delete
* remove

[#402]
== {MUST} provide a valid tag for each operation icon:check-square[text="Test" role="lime"]

Each operation must be assigned exactly one tag that categorizes it. No operation should have more than one tag.

This tag must also exist in the root specification.

[source,yaml]
----
get:
  operationId: listAccessProfiles
  tags:
    - Access Profiles
----

[#404]
== {MUST} provide a valid operationId in camelCase under the key `x-sailpoint-resource-operation-id` for each path parameter icon:check-square[text="Test" role="lime"]

Certain tools, such as the API Schema Validator and developer.sailpoint.com, rely on `x-sailpoint-resource-operation-id` to accurately locate and reference the required values for path parameters.

## API Schema Validator

When validating API responses, the tool needs to make requests to an endpoint that requires a path parameter (such as a resource `id`). Without a valid `operationId`, there is no way to programmatically determine how to retrieve a valid identifier from the system. By defining `x-sailpoint-resource-operation-id`, the validator can look up the appropriate operation to call, fetch a valid resource identifier, and then use it to execute the request for validation. This ensures that response validation is performed on actual data from the system rather than using placeholder or manually provided values.

[source, yaml]
----
parameters:
  - in: path
    name: id
    schema:
      type: string
    required: true
    description: Account ID.
    example: ef38f94347e94562b5bb8424a56397d8
    x-sailpoint-resource-operation-id: listAccounts
----

### How the API Schema Validator Resolves Resource Identifiers

When performing a lookup, the validator follows a structured process to extract the required path parameter from the response of the specified operationId. For example, if an API path requires `/accounts/{accountId}`, the corresponding `x-sailpoint-resource-operation-id: listAccounts` is necessary. The validator will attempt to resolve the `accountId` by checking the response in the following order:

1. *Exact Key Match* – It first looks for a key in the response that matches the path parameter exactly `accountId`.
2. *Fallback to Standard Identifier* `id` – If no exact match is found, it attempts to retrieve a field named id, assuming that it represents a unique identifier for the resource.
3. *Final Attempt with* `name` – If neither accountId nor id exists, it tries to use name as a last resort.
4. *Validation Failure* – If none of these keys are present in the response, the validator will error out, as it cannot resolve a valid identifier for the path parameter.

This resolution process ensures flexibility while maintaining consistency in how identifiers are determined across different API responses.

## developer.sailpoint.com

Uses the `x-sailpoint-resource-operation-id` value to improve API discoverability and documentation by linking path parameters to their respective operations. When an API requires a path parameter, such as a unique resource identifier (id), this key helps determine how the value can be retrieved. If an operation exists to list or search for the resource, its operationId can be referenced, allowing developers to programmatically obtain the required identifier before making a request to an endpoint that depends on it.

## Exceptions to this rule

This rule does not apply in the following cases:

*Enums in Path Parameters* – If the path parameter is an enum, the set of possible values is predefined and does not require lookup from an external resource. Tools can iterate through the available values without needing an associated operationId. The API Schema Validator and other tools can directly use the enum values to construct valid API requests, eliminating the need for additional lookups.

[source, yaml]
----
parameters:
  - in: path
    name: type
    schema:
      type: string
      enum:
        - ACCESS_PROFILE
        - APPLICATION
        - CAMPAIGN
        - ENTITLEMENT
        - IDENTITY
        - ROLE
        - SOD_POLICY
        - SOURCE
    required: true
    example: ACCESS_PROFILE
----

*User-Defined Path Parameters* – If the path parameter represents a value entirely determined by the user (e.g., specifying a filename when downloading or saving a file), there is no need to retrieve a resource identifier from the system. Since these values are not tied to any existing API resource, defining `x-sailpoint-resource-operation-id` would not be meaningful or applicable.


[#103]
== {MUST} write APIs using U.S. English
