[[http-status-codes-and-errors]]
= HTTP status codes and errors


[#151]
== {MUST} specify success and error responses

APIs should define the functional, business view and abstract from
implementation aspects. Success and error responses are a vital part to
define how an API is used correctly.

Therefore, you must define **all** success and service specific error
responses in your API specification. Both are part of the interface definition
and provide important information for service clients to handle standard as
well as exceptional situations. 


**Hint:** In most cases it is not useful to document all technical errors,
especially if they are not under control of the service provider. Thus unless
a response code conveys application-specific functional semantics or is used
in a none standard way that requires additional explanation, multiple error
response specifications can be combined using the following pattern:

[source,yaml]
----
responses:
  ...
  default:
    description: error occurred - see status code and problem object for more information.
    content:
      "application/problem+json":
        schema:
          $ref: 'https://sailpoint-oss.github.io/sailpoint-api-guidelines/problem-1.0.1.yaml#/Problem'
----

API designers should also think about a **troubleshooting board** as part of
the associated online API documentation. It provides information and handling
guidance on application-specific errors and is referenced via links from the
API specification. This can reduce service support tasks and contribute to
service client and provider performance.


[#321]
=== {MUST} use a standard error response object

All error responses must use the standard error response DTO object defined at 
https://github.com/sailpoint/cloud-api-client-common/blob/master/api-specs/src/main/yaml/v3/schemas/ErrorResponseDto.yaml.  
This provides a consistent error response structure that can be easily consumed by clients.


[#322]
=== {MAY} define application specific codes for the standard error response object

If using the `detailCode` within the https://github.com/sailpoint/cloud-api-client-common/blob/master/api-specs/src/main/yaml/v3/schemas/ErrorResponseDto.yaml, 
then the service owner is free to create their own logic for detail codes that will aid them in debugging issues with the service.


[#323]
=== {MUST} use the most accurate response example for each endpoint

Each endpoint must define a response example for every success and error response that can be returned.  
These examples must accurately reflect what can be returned by the endpoint.  Default examples shared across 
multiple endpoints may be used as long as they accurately reflect what can be returned by the endpoint.  If a 
default example doesn’t accurately reflect what can be returned by an endpoint, then that endpoint must 
override the default example with one that is accurate.


[#150]
== {MUST} use standard HTTP status codes

You must only use standardized HTTP status codes consistently with their
intended semantics. You must not invent new HTTP status codes.

RFC standards define ~60 different HTTP status codes with specific semantics 
(mainly {RFC-7231}#section-6[RFC7231] and {RFC-6585}[RFC 6585]) — and there
are upcoming new ones, e.g.
https://tools.ietf.org/html/draft-tbray-http-legally-restricted-status-05[draft
legally-restricted-status]. See overview on all error codes on
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[Wikipedia] or
via https://httpstatuses.com/) also inculding 'unofficial codes', e.g. used
by popular web servers like Nginx.

Below we list the most commonly used and best understood HTTP status codes,
consistent with their semantic in the RFCs. APIs should only use these to
prevent misconceptions that arise from less commonly used HTTP status codes.

**Important:** As long as your HTTP status code usage is well covered by the
semantic defined here, you should not describe it to avoid an overload with
common sense information and the risk of inconsistent definitions. Only if the
HTTP status code is not in the list below or its usage requires additional
information aside the well defined semantic, the API specification must provide
a clear description of the HTTP status code in the response.


[[success-codes]]
=== Success codes

[cols="10%,70%,20%",options="header",]
|=======================================================================
|Code |Meaning |Methods
|[[status-code-200]]{200}|
OK - this is the standard success response
|{ALL}

|[[status-code-201]]{201}|
Created - Returned on successful entity creation. You are
free to return either an empty response or the created resource in conjunction
with the Location header.
_Always_ set the Location header.
|{POST}, {PUT}

|[[status-code-202]]{202}|
Accepted - The request was successful and will be processed asynchronously.
|{POST}, {PUT}, {PATCH}, {DELETE}

|[[status-code-204]]{204}|
No content - There is no response body.
|{PUT}, {PATCH}, {DELETE}

|[[status-code-207]]{207}|
Multi-Status - The response body contains multiple status informations for
different parts of a batch/bulk request (see <<152>>).
|{POST}, ({DELETE})
|=======================================================================


[[redirection-codes]]
=== Redirection codes

[cols="10%,70%,20%",options="header",]
|=======================================================================
|Code |Meaning |Methods
|[[status-code-301]]{301}|
Moved Permanently - This and all future requests should be directed to the
given URI.
|{ALL}

|[[status-code-303]]{303}|
See Other - The response to the request can be found under another URI using a
{GET} method.
|{POST}, {PUT}, {PATCH}, {DELETE}

|[[status-code-304]]{304}|
Not Modified - indicates that a conditional GET or HEAD request would have 
resulted in 200 response if it were not for the fact that the condition evaluated 
to false, i.e. resource has not been modified since the date or version passed
via request headers If-Modified-Since or If-None-Match.
|{GET}, {HEAD}
|=======================================================================


[[client-side-error-codes]]
=== Client side error codes

[cols="10%,70%,20%",options="header",]
|=======================================================================
|Code |Meaning |Methods
|[[status-code-400]]{400}|
Bad request - generic / unknown error.  Should also be delivered in case of
input payload fails business logic validation.
|{ALL}

|[[status-code-401]]{401}|
Unauthorized - the users must log in (this often means "Unauthenticated").
|{ALL}

|[[status-code-403]]{403}|
Forbidden - the user is not authorized to use this resource.
|{ALL}

|[[status-code-404]]{404}|
Not found - the resource is not found.
|{ALL}

|[[status-code-405]]{405}|
Method Not Allowed - the method is not supported, see {OPTIONS}.
|{ALL}

|[[status-code-406]]{406}|
Not Acceptable - resource can only generate content not acceptable according
to the Accept headers sent in the request.
|{ALL}

|[[status-code-408]]{408}|
Request timeout - the server times out waiting for the resource.
|{ALL}

|[[status-code-409]]{409}|
Conflict - request cannot be completed due to conflict, e.g. when two clients
try to create the same resource or if there are concurrent, conflicting updates.
|{POST}, {PUT}, {PATCH}, {DELETE}

|[[status-code-410]]{410}|
Gone - resource does not exist any longer, e.g. when accessing a
resource that has intentionally been deleted.
|{ALL}

|[[status-code-412]]{412}|
Precondition Failed - returned for conditional requests, e.g. {If-Match} if the
condition failed. Used for optimistic locking.
|{PUT}, {PATCH}, {DELETE}

|[[status-code-415]]{415}|
Unsupported Media Type - e.g. clients sends request body without content type.
|{POST}, {PUT}, {PATCH}, {DELETE}

|[[status-code-423]]{423}|
Locked - Pessimistic locking, e.g. processing states.
|{PUT}, {PATCH}, {DELETE}

|[[status-code-428]]{428}|
Precondition Required - server requires the request to be conditional, e.g. to
make sure that the "lost update problem" is avoided (see <<181>>).
|{ALL}

|[[status-code-429]]{429}|
Too many requests - the client does not consider rate limiting and sent too
many requests (see <<153>>).
|{ALL}
|=======================================================================


[[server-side-error-codes]]
=== Server side error codes:

[cols="10%,70%,20%",options="header",]
|=======================================================================
|Code |Meaning |Methods
|[[status-code-500]]{500}|
Internal Server Error - a generic error indication for an unexpected server
execution problem (here, client retry may be sensible)
|{ALL}

|[[status-code-501]]{501}|
Not Implemented - server cannot fulfill the request (usually implies future
availability, e.g. new feature).
|{ALL}

|[[status-code-503]]{503}|
Service Unavailable - service is (temporarily) not available (e.g. if a
required component or downstream service is not available) -- client retry may
be sensible. If possible, the service should indicate how long the client
should wait by setting the {Retry-After} header.
|{ALL}
|=======================================================================


[#220]
== {MUST} use most specific HTTP status codes

You must use the most specific HTTP status code when returning information about your request 
processing status or error situations.  See the below table for examples of when to use the generic 
400 vs a more specific 4xx

See https://github.com/sailpoint/cloud-api-client-common/blob/master/design-docs/v3/definition.md#response-codes-and-headers
for a list of response codes that SailPoint prefers to use. 

If you encounter a scenario where two or more response codes are appropriate, prefer to use the response code that preserves the security of the system and does not hand out too much information to unauthorized users.


[#152]
== {MUST} use code 207 for batch or bulk requests

Some APIs are required to provide either _batch_ or _bulk_ requests using
{POST} for performance reasons, i.e. for communication and processing
efficiency. In this case services may be in need to signal multiple response
codes for each part of an batch or bulk request. As HTTP does not provide
proper guidance for handling batch/bulk requests and responses, we herewith
define the following approach:

* A batch or bulk request *always* responds with HTTP status code {207}
  unless a non-item-specific failure occurs.

* A batch or bulk request *may* return {4xx}/{5xx} status codes, if the
  failure is non-item-specific and cannot be restricted to individual items of
  the batch or bulk request, e.g. in case of overload situations or general
  service failures.

* A batch or bulk response with status code {207} *always* returns as payload
  a multi-status response containing item specific status and/or monitoring
  information for each part of the batch or bulk request.

**Note:** These rules apply _even in the case_ that processing of all
individual parts _fail_ or each part is executed _asynchronously_!

The rules are intended to allow clients to act on batch and bulk responses in
a consistent way by inspecting the individual results. We explicitly reject
the option to apply {200} for a completely successful batch as proposed in
Nakadi's https://nakadi.io/manual.html#/event-types/name/events_post[`POST
/event-types/{name}/events`] as short cut without inspecting the result, as we
want to avoid  risks and expect clients to handle partial
batch failures anyway.

The bulk or batch response may look as follows:

[source,yaml]
----
BatchOrBulkResponse:
  description: batch response object.
  type: object
  properties:
    items:
      type: array
      items:
        type: object
        properties:
          id:
            description: Identifier of batch or bulk request item.
            type: string
          status:
            description: >
              Response status value. A number or extensible enum describing
              the execution status of the batch or bulk request items.
            type: string
            x-extensible-enum: [...] 
          description:
            description: >
              Human readable status description and containing additional
              context information about failures etc.
            type: string
        required: [id, status]
----

*Note*: while a _batch_ defines a collection of requests triggering
independent processes, a _bulk_ defines a collection of independent
resources created or updated together in one request. With respect to
response processing this distinction normally does not matter.


[#153]
== {MUST} use code 429 with headers for rate limits

APIs that wish to manage the request rate of clients must use the {429} (Too
Many Requests) response code, if the client exceeded the request rate (see
{RFC-6585}[RFC 6585]). Such responses must also contain header information
providing further details to the client. There are two approaches a service
can take for header information:

* Return a {Retry-After} header indicating how long the client ought to wait
  before making a follow-up request. The Retry-After header can contain a HTTP
  date value to retry after or the number of seconds to delay. Either is
  acceptable but APIs should prefer to use a delay in seconds.
* Return a trio of `X-RateLimit` headers. These headers (described below) allow
  a server to express a service level in the form of a number of allowing
  requests within a given window of time and when the window is reset.

The `X-RateLimit` headers are:

* `X-RateLimit-Limit`: The maximum number of requests that the client is
  allowed to make in this window.
* `X-RateLimit-Remaining`: The number of requests allowed in the current
  window.
* `X-RateLimit-Reset`: The relative time in seconds when the rate limit window
  will be reset. **Beware** that this is different to Github and Twitter's
  usage of a header with the same name which is using UTC epoch seconds
  instead.

The reason to allow both approaches is that APIs can have different
needs. Retry-After is often sufficient for general load handling and
request throttling scenarios and notably, does not strictly require the
concept of a calling entity such as a tenant or named account. In turn
this allows resource owners to minimise the amount of state they have to
carry with respect to client requests. The 'X-RateLimit' headers are
suitable for scenarios where clients are associated with pre-existing
account or tenancy structures. 'X-RateLimit' headers are generally
returned on every request and not just on a 429, which implies the
service implementing the API is carrying sufficient state to track the
number of requests made within a given window for each named entity.


[#176]
== {MUST} support problem JSON

TBD


[#177]
== {MUST} not expose stack traces

Stack traces contain implementation details that are not part of an API,
and on which clients should never rely. Moreover, stack traces can leak
sensitive information that partners and third parties are not allowed to
receive and may disclose insights about vulnerabilities to attackers.
