[[hypermedia]]
= Hypermedia


[#162]
== {MUST} use REST maturity level 2

We strive for a good implementation of
http://martinfowler.com/articles/richardsonMaturityModel.html#level2[REST
Maturity Level 2] as it enables us to build resource-oriented APIs that
make full use of HTTP verbs and status codes. You can see this expressed
by many rules throughout these guidelines, e.g.:

* <<138>>
* <<141>>
* <<148>>
* <<150>>

Although this is not HATEOAS, it should not prevent you from designing
proper link relationships in your APIs as stated in rules below.


[#217]
== {SHOULD} use full, absolute URI

Links to other resource should always use full, absolute URI.

*Motivation*: Exposing any form of relative URI (no matter if the relative
URI uses an absolute or relative path) introduces avoidable client side
complexity. It also requires clarity on the base URI, which might not be given
when using features like embedding subresources. The primary advantage of
non-absolute URI is reduction of the payload size, which is better achievable
by following the recommendation to use <<156,gzip compression>>


[#164]
== {MUST} use common hypertext controls

When embedding links to other resources into representations you must use the
common hypertext control object. It contains at least one attribute:

* [[href]]{href}: The URI of the resource the hypertext control is linking to.
  All our API are using HTTP(s) as URI scheme.

In API that contain any hypertext controls, the attribute name {href} is
reserved for usage within hypertext controls.

The schema for hypertext controls can be derived from this model:

[source,yaml]
----
HttpLink:
  description: A base type of objects representing links to resources.
  type: object
  properties:
    href:
      description: Any URI that is using http or https protocol
      type: string
      format: uri
  required:
    - href
----

The name of an attribute holding such a `HttpLink` object specifies the
relation between the object that contains the link and the linked
resource. Implementations should use names from the {link-relations}[IANA
Link Relation Registry] whenever appropriate. As IANA link relation
names use hyphen-case notation, while this guide enforces snake_case
notation for attribute names, hyphens in IANA names have to be replaced
with underscores (e.g. the IANA link relation type `version-history`
would become the attribute `version_history`)

Specific link objects may extend the basic link type with additional
attributes, to give additional information related to the linked
resource or the relationship between the source resource and the linked
one.

E.g. a service providing "Person" resources could model a person who is
married with some other person with a hypertext control that contains
attributes which describe the other person (`id`, `name`) but also the
relationship "spouse" between the two persons (`since`):

[source,json]
----
{
  "id": "446f9876-e89b-12d3-a456-426655440000",
  "name": "Peter Mustermann",
  "spouse": {
    "href": "https://...",
    "since": "1996-12-19",
    "id": "123e4567-e89b-12d3-a456-426655440000",
    "name": "Linda Mustermann"
  }
}
----

Hypertext controls are allowed anywhere within a JSON model. While this
specification would allow
http://stateless.co/hal_specification.html[HAL], we actually don't
recommend/enforce the usage of HAL anymore as the structural separation
of meta-data and data creates more harm than value to the
understandability and usability of an API.


[#166]
== {MUST} not use link headers with JSON entities

For flexibility and precision, we prefer links to be directly embedded in the
JSON payload instead of being attached using the uncommon link header syntax.
As a result, the use of the {RFC-8288}#section-3[`Link` Header defined by RFC
8288] in conjunction with JSON media types is forbidden.
