[[json-guidelines]]
= JSON guidelines

These guidelines provides recommendations for defining JSON data at SailPoint.
JSON here refers to {RFC-7159}[RFC 7159] (which updates {RFC-4627}[RFC 4627]),
the "application/json" media type and custom JSON media types defined for APIs.
The guidelines clarifies some specific cases to allow SailPoint JSON data to have
an idiomatic form across teams and services.

The first some of the following guidelines are about property names, the later
ones about values.


[#120]
== {SHOULD} pluralize array names

Names of arrays should be pluralized to indicate that they contain multiple values.
This implies in turn that object names should be singular.


[#118]
== {MUST} property names must be ASCII camelCase

Property names are restricted to ASCII strings.  The first character must be a lower case letter, there must not be any spaces, and new words should start with a capital letter instead of a space.  For example, “new client table” would be “newClientTable” in camelCase.

“ID” is common in field names, and must be presented in camel case as follows:

* If “ID” appears as the first word, then it is entirely lowercase (ex. “id”).
* If “ID” appears after the first word, then the “I” is capitalized and the “d” is lowercase (ex. “userId”).


[#240]
== {MUST} declare enum values using UPPER_SNAKE_CASE string 

Enumerations must be represented as `string` typed OpenAPI definitions of 
request parameters or model properties.
Enum values (using `enum` or {x-extensible-enum}) need to consistently use 
the upper-snake case format, e.g. `VALUE` or `YET_ANOTHER_VALUE`. 
This approach allows to clearly distinguish values from properties or other elements.

**Exception:** This rule does not apply for case sensitive values sourced from outside 
API definition scope, e.g. for language codes from {ISO-639-1}[ISO 639-1], or when 
declaring possible values for a <<137,rule 137>> [`sort` parameter].

[#216]
== {SHOULD} define maps using `additionalProperties`

A "map" here is a mapping from string keys to some other type. In JSON this is
represented as an object, the key-value pairs being represented by property
names and property values. In OpenAPI schema (as well as in JSON schema) they
should be represented using additionalProperties with a schema defining the
value type. Such an object should normally have no other defined properties.

The map keys don't count as property names in the sense of <<118,rule 118>>,
and can follow whatever format is natural for their domain. Please document
this in the description of the map object's schema.

Here is an example for such a map definition (the `translations` property):

```yaml
components:
  schemas:
    Message:
      description:
        A message together with translations in several languages.
      type: object
      properties:
        message_key:
          type: string
          description: The message key.
        translations:
          description:
            The translations of this message into several languages.
            The keys are [IETF BCP-47 language tags](https://tools.ietf.org/html/bcp47).
          type: object
          additionalProperties:
            type: string
            description:
              the translation of this message into the language identified by the key.
```

An actual JSON object described by this might then look like this:
```json
{ "message_key": "color",
  "translations": {
    "de": "Farbe",
    "en-US": "color",
    "en-GB": "colour",
    "eo": "koloro",
    "nl": "kleur"
  }
}
```


[#122]
== {MUST} not use `null` for boolean properties

Schema based JSON properties that are by design booleans must not be
presented as nulls. A boolean is essentially a closed enumeration of two
values, true and false. If the content has a meaningful null value,
strongly prefer to replace the boolean with enumeration of named values
or statuses - for example accepted_terms_and_conditions with true or
false can be replaced with terms_and_conditions with values yes, no and
unknown.


[#310]
== {MUST} define a default value for boolean properties

All boolean properties must have a default value defined


[#311]
== {SHOULD} avoid using qualifying verbs

Avoid using qualifying verbs, especially on boolean fields, e.g. 

* Discouraged: isEnabled
* Recommended: enabled


[#312]
== {SHOULD} use positive semantics for boolean fields

The name of a Boolean field should preferably express semantics such that true indicates a positive attribute, action, capability, etc. 

* Discouraged: "disabled": true
* Recommended: "enabled": false


[#313]
== {MUST} use a field name that suggests the value type when referencing an object

When a field contains an ID or reference to an foreign object, not the parent object, the field name should suggest the value type: 

* Discouraged: "owner": "2c90b0c06460804b016460f9f59b0015"
* Recommended: "ownerId": "2c90b0c06460804b016460f9f59b0015"

For example, the following request/response for an account object uses the proper naming for object references. 

“id” refers to the account object being requested, and all other object references include the object reference name (i.e. sourceId, identityId, etc.)

[source,json]
----
{
    "id": "id12345",
    "name": "aName",
    "created": "2019-08-24T14:15:22Z",
    "modified": "2019-08-24T14:15:22Z",
    "sourceId": "2c9180835d2e5168015d32f890ca1581",
    "identityId": "2c9180835d2e5168015d32f890ca1581",
    "attributes": { },
    "authoritative": true,
    "description": "string",
    "disabled": true,
    "locked": true,
    "nativeIdentity": "string",
    "systemAccount": true,
    "uncorrelated": true,
    "uuid": "string",
    "manuallyCorrelated": true,
    "hasEntitlements": true
}
----

[#314]
== {SHOULD} name references to foreign objects as <objectName>Ref

* Discouraged: "launcher": "frank.dogs"
* Recommended: "launcherRef": {"resource": "identities", "type": "ALIAS", "value": "frank.dogs"}

Example
[source,json]
----
{
    "id": "2c9180857182305e0171993735622948",
    "name": "Alison Ferguso",
    "alias": "alison.ferguso",
    "email": "alison.ferguso@acme-solar.com",
    "status": "Active",
    "managerRef": {
        "type": "IDENTITY",
        "id": "2c9180a46faadee4016fb4e018c20639",
        "name": "Thomas Edison"
    },
    "attributes":[]
}
----


[#315]
== {SHOULD} avoid using nested objects

In general, we discourage nesting DTOs inside others. This has typically led to bloated DTOs and made it complicated to 
enforce authorization requirements and other business rules around those nested objects. It is preferable instead for the 
DTO to have a field containing an id or reference that allows the nested object to be separately fetched.

It is recognized, of course, that particular use cases may require nesting objects inside each other. For example, if a 
UI module needs to display data from a set of 100 IdentityRequests and their child IdentityRequestItems, it makes no 
sense to require the UI to make one API call to get the list of IdentityRequests and then 100 additional calls to get the 
IdentityRequestItems for each.

It is preferable in these cases to use a summary DTO for the nested objects that contains the minimum amount of detail 
required to support the known or plausible use case(s). For example, if the only reason I need to include the owner of 
an object is so the caller can display their first and last name, then it is better to do something like the following:

[source,json]
----
{
    ...
    "owner": {
        "type": "IDENTITY",
        "id": "2c90b0c06460804b016460f9f59b001",
        "firstName": "Frank",
        "lastName": "Dogs"
    }
}
----

One particular valid use of nested objects occurs when a DTO abstracts over a set of types that may have significantly 
different attributes. In this case the non-general fields of the DTO should be pushed down to a nested object, with a 
type field on the main object being used as a discriminator. For example, if a DTO could represent either an Access Profile 
or a Role, the former case could be implemented as follows:

[source,json]
----
{
     ...
     "type": "ACCESS_PROFILE",
     ...
     "accessProfileInfo": {
          "appRefs": ["app1", "app2"]
     },
     "roleInfo": null
}
----

[#316]
== {MUST} define a default for optional values

All properties must define a default value for optional properties.  This must documented in the specification so clients 
know what value will be used should they ignore a property.


[#317]
== {MUST} define the “required” attribute for request/response objects and parameters

All request/response schemas MUST define the “required” attribute for each property and parameter per the OpenAPI specification.

For request/response objects, see https://swagger.io/docs/specification/data-models/data-types/#required. If all properties within an object are optional, then the "required" attribute may be omitted.

For path and query parameters, see https://swagger.io/docs/specification/describing-parameters/

Generally, query parameters should be optional, but there are cases where a query parameter is required.  In these cases, 
make sure to set the “required” attribute for the query parameters to true.


[#123]
== {MUST} use same semantics for `null` and absent properties

TBD


[#318]
== {MUST} use the “nullable” attribute for properties that can be null

If a property or parameter can return `null`, then it must have the `nullable: true` OpenAPI property.


[#124]
== {MUST} not use `null` for empty arrays

Empty array values can unambiguously be represented as the empty list, `[]`.


[#126]
== {SHOULD} define dates properties compliant with RFC 3339

Use the date and time formats defined by {RFC-3339}#section-5.6[RFC 3339]:

* for "date" use strings matching
`date-fullyear "-" date-month "-" date-mday`, for example: `2015-05-28`
* for "date-time" use strings matching `full-date "T" full-time`, for
example `2015-05-28T14:07:17Z`

Note that the
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types[OpenAPI format] 
"date-time" corresponds to "date-time" in the RFC) and `2015-05-28`
for a date (note that the OpenAPI format "date" corresponds to "full-date" in
the RFC). Both are specific profiles, a subset of the international standard
{ISO-8601}[ISO 8601].

A zone offset may be used (both, in request and responses) -- this is simply
defined by the standards. However, we encourage restricting dates to UTC and
without offsets. For example `2015-05-28T14:07:17Z` rather than
`2015-05-28T14:07:17+00:00`. From experience we have learned that zone offsets
are not easy to understand and often not correctly handled. Note also that
zone offsets are different from local times that might be including daylight
saving time. Localization of dates should be done by the services that provide
user interfaces, if required.

When it comes to storage, all dates should be consistently stored in UTC
without a zone offset. Localization should be done locally by the services that
provide user interfaces, if required.

Sometimes it can seem data is naturally represented using numerical timestamps,
but this can introduce interpretation issues with precision, e.g. whether to
represent a timestamp as 1460062925, 1460062925000 or 1460062925.000. Date
strings, though more verbose and requiring more effort to parse, avoid this
ambiguity.


[#127]
== {SHOULD} define time durations and intervals properties conform to ISO 8601

Schema based JSON properties that are by design durations and intervals could
be strings formatted as recommended by {ISO-8601}[ISO 8601]
({RFC-3339}#appendix-A[Appendix A of RFC 3339 contains a grammar] for durations).
