[[meta-information]]
= Meta information


[#218]
== {MUST} contain API meta information
API specifications must contain the following OpenAPI meta information
to allow for API management:

- `#/info/title` as (unique) identifying, functional descriptive name of the API
- `#/info/version` to distinguish API specifications versions following
  <<116, semantic rules>>
- `#/info/description` containing a proper description of the API
- `#/info/x-audience` intended target audience of the API (<<219, see rule 219>>)

[NOTE]
====
We’ll automatically generate `#/info/contact/*` when creating public Open API spec.
====


[#116]
== {MUST} use semantic versioning

[NOTE]
====
We’ll automatically generate the global `#/info/version` when creating public Open API spec. 
Each individual endpoint spec author need not worry about this attribute.
====


[#219]
== {MUST} provide API audience

Each API must be classified with respect to the intended target audience 
supposed to consume the API, to facilitate differentiated standards on APIs 
for discoverability, changeability, quality of design and documentation, as 
well as permission granting. We differentiate the following API audience 
groups with clear organisational and legal boundaries: 

`internal-company`
`external-public`

[NOTE]
====
This is only for documentation generation purposes and not related to 
authorization—authz concerns must be addressed with normal policies.
====

[source,yaml]
----
/info/x-audience:
  type: string
  x-extensible-enum:
    - internal-company
    - external-public
  description: |
    Intended target audience of the API. Relevant for standards around
    quality of design and documentation, reviews, discoverability,
    changeability.
----

[NOTE]
====
Exactly one audience per API specification is allowed. For this reason 
a smaller audience group is intentionally included in the wider group 
and thus does not need to be declared additionally. If parts of your API 
have a different target audience, we recommend to split API specifications 
along the target audience — even if this creates redundancies (rationale (internal link)).
====


Example:

[source,yaml]
----
openapi: 3.0.1
info:
  x-audience: internal-company
  title: Service to Service API
  description: API for <...>
  version: 1.2.4
  <...>
----

