[[api-naming]]
= API naming


[#223]
== {MUST-SHOULD} use functional naming schema

TBD


[#129]
== {MUST} use lowercase separate words with hyphens for path segments

* Use kebab-case for path segments
* Use {camelCase} with surrounding brackets to indicate path parameters

Example:

[source,http]
----
/shipment-orders/{shipmentOrderId}
----


[#130]
== {MUST} camelCase for query parameters

Examples:

[source]
----
customerNumber, orderId, billingAddress
----

We need to have a consistent look and feel for our APIs.  In the case of query parameters, 
which can reference actual properties in the response object, camelCase preserves a consistent look and feel.


[#134]
== {MUST} pluralize resource names

When defining a path segment for a collection, the resource name must be plural to indicate it is a collection of resources.

Example:

`/users`, `/companies/{companyId}/employees/{employeeId}`


[#135]
== {MUST} not use `/api` as base path

In most cases, all resources provided by a service are part of the
public API, and therefore should be made available under the root "/"
base path.

If the service should also support non-public, internal APIs
— for specific operational support functions, for example — we encourage 
you to maintain two different API specifications and provide
<<219, API audience>>. For both APIs, you should not use `/api` as base path.

We see API's base path as a part of deployment variant configuration.
Therefore, this information has to be declared in the
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#server-object[server object].


[#136]
== {MUST} use normalized paths without empty path segments and trailing slashes

You must not specify paths with duplicate or trailing slashes, e.g.
`/customers//addresses` or `/customers/`. As a consequence, you must also not
specify or use path variables with empty string values.

*Reasoning:* Non standard paths have no clear semantics. As a result, behavior
for non standard paths varies between different HTTP infrastructure components
and libraries. This may leads to ambiguous and unexpected results during
request handling and monitoring.

We recommend to implement services robust against clients not following this
rule. All services *should* https://en.wikipedia.org/wiki/URI_normalization[normalize]
request paths before processing by removing duplicate and trailing slashes.
Hence, the following requests should refer to the same resource:

[source,http]
----
GET /orders/{orderId}
GET /orders/{orderId}/
GET /orders//{orderId}
----

**Note:** path normalization is not supported by all framework out-of-the-box.
Services are required to support at least the normalized path while rejecting
all alternatives paths, if failing to deliver the same resource.


[#137]
== {MUST} stick to conventional query parameters

If you provide query support for searching, sorting, filtering, and
paginating, you must stick to the following naming conventions:

Pagination

* `limit`: Integer that specifies the maximum number of results to return. If not specified a default limit will be used.
* `offset`: Integer that specifies the offset of the first result from the beginning of the collection
* `count`: Boolean that indicates whether a total count will be returned, factoring in any filter parameters, in the X-Total-Count response header.

`filters`: an item will only be included in the returned array if the filters expression evaluates 
to true for that item.  Each endpoint that implements filters must clearly define in the API 
spec what operations and fields are supported.

`sorters`: a set of comma-separated field names. Each field name may be optionally prefixed with a "-" 
character, which indicates the sort is descending based on the value of that field. Otherwise, the sort 
is ascending.  Each endpoint that implements sorters must clearly define which fields are supported.

See https://developer.sailpoint.com/docs/api/standard-collection-parameters/#paginating-results
for implementation details for each of the above parameters. 

Note:  Additional query parameters are allowed, but effort should be made to fit them within the five listed above.


[#319]
== {MUST} Customer org name must never appear in the path of public APIs

The customer organization is provided in the session context that is generated on the back end, and therefore does not need to be in the URL.