[[performance]]
= Performance

[#157]
== {SHOULD} support partial responses via filtering

Depending on your use case and payload size, you can significantly reduce
network bandwidth need by supporting filtering of returned entity fields.
Here, the client can explicitly determine the subset of fields he wants to
receive via the {fields} query parameter. (It is analogue to
https://graphql.org/learn/queries/#fields[GraphQL `fields`] and simple
queries, and also applied, for instance, for
https://cloud.google.com/storage/docs/json_api/v1/how-tos/performance#partial-response[Google
Cloud API's partial responses].)


[[unfiltered]]
=== Unfiltered

[source,http]
----
GET http://api.example.org/users/123 HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

{
  "id": "cddd5e44-dae0-11e5-8c01-63ed66ab2da5",
  "name": "John Doe",
  "address": "1600 Pennsylvania Avenue Northwest, Washington, DC, United States",
  "birthday": "1984-09-13",
  "friends": [ {
    "id": "1fb43648-dae1-11e5-aa01-1fbc3abb1cd0",
    "name": "Jane Doe",
    "address": "1600 Pennsylvania Avenue Northwest, Washington, DC, United States",
    "birthday": "1988-04-07"
  } ]
}
----


[[filtered]]
=== Filtered

[source,http]
----
GET http://api.example.org/users/123?fields=(name,friends(name)) HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

{
  "name": "John Doe",
  "friends": [ {
    "name": "Jane Doe"
  } ]
}
----

The {fields} query parameter determines the fields returned with the response
payload object. For instance, `(name)` returns `users` root object with only
the `name` field, and `(name,friends(name))` returns the `name` and the nested
`friends` object with only its `name` field.

OpenAPI doesn't support you in formally specifying different return object
schemes depending on a parameter. When you define the field parameter, we
recommend to provide the following description: `Endpoint supports filtering
of return object fields as described in
[Rule #157](https://opensource.zalando.com/restful-api-guidelines/#157)`

The syntax of the query {fields} value is defined by the following
https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form[BNF] grammar.

[source,bnf]
----
<fields>            ::= [ <negation> ] <fields_struct>
<fields_struct>     ::= "(" <field_items> ")"
<field_items>       ::= <field> [ "," <field_items> ]
<field>             ::= <field_name> | <fields_substruct>
<fields_substruct>  ::= <field_name> <fields_struct>
<field_name>        ::= <dash_letter_digit> [ <field_name> ] 
<dash_letter_digit> ::= <dash> | <letter> | <digit>
<dash>              ::= "-" | "_"
<letter>            ::= "A" | ... | "Z" | "a" | ... | "z"
<digit>             ::= "0" | ... | "9"
<negation>          ::= "!"
----

**Note:** Following the
https://en.wikipedia.org/wiki/Principle_of_least_astonishment[principle of
least astonishment], you should not define the {fields} query parameter using
a default value, as the result is counter-intuitive and very likely not
anticipated by the consumer.


[#158]
== {SHOULD} allow optional embedding of sub-resources

Embedding related resources (also know as _Resource expansion_) is a
great way to reduce the number of requests. In cases where clients know
upfront that they need some related resources they can instruct the
server to prefetch that data eagerly. Whether this is optimized on the
server, e.g. a database join, or done in a generic way, e.g. an HTTP
proxy that transparently embeds resources, is up to the implementation.

See <<137>> for naming, e.g. "embed" for steering of embedded
resource expansion. Please use the
https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form[BNF] grammar, as
already defined above for filtering, when it comes to an embedding query
syntax.

Embedding a sub-resource can possibly look like this where an order
resource has its order items as sub-resource (/order/\{orderId}/items):

[source,http]
----
GET /order/123?embed=(items) HTTP/1.1

{
  "id": "123",
  "_embedded": {
    "items": [
      {
        "position": 1,
        "sku": "1234-ABCD-7890",
        "price": {
          "amount": 71.99,
          "currency": "EUR"
        }
      }
    ]
  }
}
----
