[[security]]
= Security


[#104]
== {MUST} secure endpoints with OAuth 2.0 icon:check-square[text="Test" role="lime"]

Every public API endpoint must be secured using OAuth 2.0.

For information on adding new oauth2 scopes visit https://sailpoint.atlassian.net/wiki/spaces/PLAT/pages/1713963123/Defining+Scopes+for+API+Authorization[Defining Scopes for API Authorization, role=external, window=_blank].

The following code snippet shows how to define the authorization scheme using a bearer token (e.g. JWT token).

[source,yaml]
----
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: |
        OAuth2 Bearer token (JWT).
      flows:
        clientCredentials:
          tokenUrl: https://tenant.api.identitynow.com/oauth/token
          scopes:
            "sp:scopes:default": "default scope"
            "sp:scopes:all": "access to all scopes"
        authorizationCode:
          authorizationUrl: https://tenant.identitynow.com/oauth/authorize
          tokenUrl: https://tenant.api.identitynow.com/oauth/token
          scopes:
            "sp:scopes:default": "default scope"
            "sp:scopes:all": "access to all scopes"
----

The next code snippet applies this security scheme to all API endpoints. The bearer token of the client must have additionally the scopes scope_1 and scope_2.

[source,yaml]
----
security:
    - UserContextAuth: [ scope_1, scope_2 ]
----


[#105]
== {MUST} define and assign permissions (scopes) icon:check-square[text="Test" role="lime"]

Each endpoint must document every https://github.com/sailpoint/cloud-api-client-common/blob/master/api-specs/src/main/yaml/beta/securitySchemes/OAuth2.yaml[AMS right, role=external, window=_blank] 
needed to access the endpoint.  If creating a new AMS right that doesn’t exist in the list, then it must be added to the list first.

To appropriately document AMS rights on an endpoint, use the following OpenAPI properties:
[source,yaml]
----
security:
  - UserContextAuth:
     - 'idn:task-definition:read'
     - 'idn:task-definition:write'
----

A full example on an endpoint might look like this:
[source,yaml]
----
get:
  tags:
    - tenants
  summary: Get Tenant
  description: Get tenant object based on current auth token
  operationId: getTenant
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '../schemas/Tenant.yaml'
  security:
    - UserContextAuth:
        - 'idn:accounts:read'
----


[#306]
== {MUST} Document necessary license add-on to use an API collection

If an API collection requires additional product licenses to enable the feature, then each required license must be documented in the API collection description.


[#225]
== {MUST} follow naming convention for permissions (scopes)

TBD
