[[security]]
= Security


[#104]
== {MUST} secure endpoints with OAuth 2.0 icon:check-square[text="Test" role="lime"]

Every public API endpoint must be secured using OAuth 2.0. We have defined two security schemas, *userAuth* and *applicationAuth*. In the rare case that an endpoint does not require authentication, and is completely open to the public, then an empty object can be used instead.

* *userAuth* is the authentication mechanism that assigns a user context to a token, such as a Personal Access Token or OAuth token granted via authorization code.

* *applicationAuth* is the authentication mechanism that provides a token that does not have a user context. This is a result of the OAuth client credentials grant flow.

* *{}* is how we indicate that an endpoint does not require authentication to access.

Each endpoint must select one or both of the security schemes depending on which one(s) it supports. For example, if an endpoint supports only *userAuth*, then the path would be defined as follows:

[source,yaml]
----
get:
  operationId: getAccessProfile
  tags:
    - Access Profiles
  summary: Get an Access Profile
  description: >-
    This API returns an Access Profile by its ID.
  security:
    - userAuth: [idn:access-profile:read]
----

If the endpoint supports both security schemes, then it would be defined as follows:

[source,yaml]
----
get:
  operationId: getAccessProfile
  tags:
    - Access Profiles
  summary: Get an Access Profile
  description: >-
    This API returns an Access Profile by its ID.
  security:
    - userAuth: [idn:access-profile:read]
    - applicationAuth: [idn:access-profile:read]
----

If the endpoint does not require authentication, then it would be defined as follows:

[source,yaml]
----
get:
  operationId: getAccessProfile
  tags:
    - Access Profiles
  summary: Get an Access Profile
  description: >-
    This API returns an Access Profile by its ID.
  security:
    - {}
----


[#105]
== {MUST} define and assign permissions (scopes) icon:check-square[text="Test" role="lime"]

Each endpoint must document every scope needed to access the endpoint.  See https://sailpoint.atlassian.net/wiki/spaces/PLAT/pages/1713963123/Defining+Scopes+for+API+Authorization[Defining Scopes for API Authorization, role=external, window=_blank] for more information on adding new scopes.

To appropriately document a scope on an endpoint, use the following OpenAPI properties:
[source,yaml]
----
security:
  - userAuth:
     - 'idn:task-definition:read'
     - 'idn:task-definition:manage'
----

A full example on an endpoint might look like this:
[source,yaml]
----
get:
  tags:
    - tenants
  summary: Get Tenant
  description: Get tenant object based on current auth token
  operationId: getTenant
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '../schemas/Tenant.yaml'
  security:
    - userAuth:
        - 'idn:accounts:read'
----

[#326]
== {MUST} define user levels (capabilities) needed by an endpoint

Each endpoint that specifies *userAuth* as one of the allowed security types must also document the user levels required to access the endpoint. See the https://documentation.sailpoint.com/saas/help/common/users/user_level_matrix.html[user level matrix, role=external, window=_blank] for more information.

To appropriately document user level(s) on an endpoint, use the *x-sailpoint-userLevels* attribute in the path definition. The *technical name* must be used as seen in the user level matrix (ex. ORG_ADMIN instead of Admin).

[source,yaml]
----
x-sailpoint-userLevels:
  - ORG_ADMIN
  - SOURCE_ADMIN
----

A full example on an endpoint might look like this:
[source,yaml]
----
get:
  tags:
    - tenants
  summary: Get Tenant
  description: Get tenant object based on current auth token
  operationId: getTenant
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '../schemas/Tenant.yaml'
  security:
    - userAuth:
        - 'idn:accounts:read'
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - SOURCE_ADMIN
----


[#306]
== {MUST} Document necessary license add-on to use an API collection

If an API collection requires additional product licenses to enable the feature, then each required license must be documented in the API collection description.


[#225]
== {MUST} follow naming convention for permissions (scopes)

TBD
